language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"

branches:
    only:
        - master
        - develop

install:
    - pip install -IM pylama

script:
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then make audit; fi"
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then make audit; fi"
    - make t
